name:                bioinformatics
version:             0.1.0.0
github:              "githubuser/bioinformatics"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bioinformatics#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - array >= 0.5 && < 0.6
    - containers >= 0.5 && < 0.6
    - text >= 1.2 && < 1.3
    - mtl >= 2.2 && < 2.3
    - MonadRandom >= 0.5 && < 0.6
    - transformers >= 0.5 && < 0.6

executables:
  bioinformatics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bioinformatics
    - array >= 0.5 && < 0.6
    - mtl >= 2.2 && < 2.3

tests:
  bioinformatics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-type-defaults
    dependencies:
    - bioinformatics
    - array >= 0.5 && < 0.6
    - hspec >= 2.5 && < 2.6
    - QuickCheck >= 2.11 && < 2.12
